### PR TITLE
Set up a "Hello world" project as one app with Webpack

### PR DESCRIPTION
**Pull request by Paul-js-hub**
### In this project I:
- Created a new Rails app called 'hello-rails-react'.
- Created a babel.config.js in the root folder.
- Updated webpack.config.js to include the babel-loader.
- Implemented a connection between a Ruby on Rails back-end and React front-end.

### CODE REVIEW

**Review by Ismailco — CHANGES_REQUESTED** [review]
### Hi @Paul-js-hub, 

Good job so far 👍🏼 
You still need to work on some issues to go to the next project, but you are almost there!

## Highlights

✔️  No linter errors
✔️ Used correct workflow
✔️ Work documented professionally

## Required Changes ♻️
- [ ] Your javascript folder should have the `<App>` component present kindly make sure to create it, and include only the necessary code on the `application.js` file

Screenshot_20230224_075505

- [ ] Kindly make sure to return only one random message from the API, your using `array.map()` in the `<Greeting>` component instead you should just render the string (not array) returned from the API

Screenshot_20230224_075358

_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by Paul-js-hub** [comment]
Hi, @Ismailco thanks for the review and I will make the changes. I don't understand the second change because if you refresh the page a random message is displayed as a string but not as an array.

**Comment by Ismailco** [comment]
> Hi, @Ismailco thanks for the review and I will make the changes. I don't understand the second change because if you refresh the page a random message is displayed as a string but not as an array.

@Paul-js-hub, Sorry for this You're using `Array.map()` because the returned greeting is an array, that's totally fine. I confused this with something else. You just need to Fix the `application.js` and create an `App` component

**Comment by Paul-js-hub** [comment]
@Ismailco, thanks for your favorable response. I have made the changes you asked for.

**Review by mahbubul14 — APPROVED** [review]
# Project Approved :trophy: :tada: 

Hi @Paul-js-hub, 

Your project is complete!  You have done it exceptionally well. it's time to merge it :100: 
Congratulations! 🎉 

### To Highlight :+1: 

:heavy_check_mark: No linter error.
:heavy_check_mark: Descriptive readme file.
:heavy_check_mark: Well-implemented requirements.

### Optional suggestions :arrow_down_small: 

Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better.

* N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification. You can also connect with me on [slack](https://microverse-students.slack.com/team/U01J39GL614)

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

**Pull request merged**
